import type { World } from "./types";

/**
 * The Entry world. Each stage is a "village" on the map; lessons unlock in order.
 * Positions are king-less (loaded with skipValidation) so a pawn can stand alone
 * on an otherwise empty board, exactly as a beginner first meets it.
 *
 * Adding content = adding data here. No component changes required.
 */
export const ENTRY_WORLD: World = [
  {
    id: "pawn-village",
    name: "Pawn Village",
    tagline: "The soul of chess",
    icon: "♟",
    accent: "#769656",
    lessons: [
      {
        id: "pawn-march",
        title: "The Pawn's March",
        blurb: "How the humble pawn moves",
        icon: "♟",
        steps: [
          {
            kind: "say",
            text: "Meet the pawn — the soul of chess. It only ever marches forward, never backward.",
            board: "8/8/8/8/8/8/4P3/8 w - - 0 1",
            spotlight: ["e2"],
          },
          {
            kind: "do",
            text: "From its home square a pawn may step one or two squares forward. Walk it up to e5.",
            say: "From its home square a pawn may step one or two squares forward. Walk it up to e5.",
            board: "8/8/8/8/8/8/4P3/8 w - - 0 1",
            goal: { type: "reach", square: "e5" },
            spotlight: ["e3", "e4"],
            hint: "Click the pawn, then a square ahead. Its first move can be two squares: e2 to e4.",
          },
          {
            kind: "say",
            text: "After that first leap, a pawn only steps one square at a time.",
          },
        ],
        tip: "Pawns move straight forward — one square, or two on their very first move.",
      },
      {
        id: "pawn-promote",
        title: "Crowning Glory",
        blurb: "Reach the end, become a queen",
        icon: "♛",
        steps: [
          {
            kind: "say",
            text: "A pawn brave enough to reach the far side is rewarded — it transforms into a far stronger piece.",
            board: "8/4P3/8/8/8/8/8/8 w - - 0 1",
            spotlight: ["e7", "e8"],
          },
          {
            kind: "do",
            text: "Push the pawn to the last rank and let it become a Queen.",
            board: "8/4P3/8/8/8/8/8/8 w - - 0 1",
            goal: { type: "promote" },
            spotlight: ["e8"],
            hint: "Move the e7 pawn to e8 — here it promotes straight to a Queen.",
          },
          {
            kind: "say",
            text: "You usually choose a Queen, the most powerful piece — but a Rook, Bishop, or Knight are also allowed.",
          },
        ],
        tip: "Reach the last rank to promote — a new Queen is almost always the right choice.",
      },
      {
        id: "pawn-capture",
        title: "First Blood",
        blurb: "Pawns strike sideways",
        icon: "⚔",
        steps: [
          {
            kind: "say",
            text: "Pawns capture in a way all their own — not how they move.",
            board: "8/8/8/3p4/4P3/8/8/8 w - - 0 1",
            spotlight: ["d5"],
          },
          {
            kind: "do",
            text: "A pawn captures one square diagonally forward, never straight ahead. Take the enemy pawn on d5.",
            board: "8/8/8/3p4/4P3/8/8/8 w - - 0 1",
            goal: { type: "move", uci: ["e4d5"] },
            spotlight: ["d5"],
            hint: "Move your e4 pawn diagonally onto d5 to capture it.",
          },
          {
            kind: "say",
            text: "So a pawn moves straight but strikes sideways. Keep that difference in mind.",
          },
        ],
        tip: "Pawns move forward but capture diagonally.",
      },
      {
        id: "pawn-duel",
        title: "The Standoff",
        blurb: "Break a blocked pawn",
        icon: "⚑",
        steps: [
          {
            kind: "say",
            text: "When two pawns meet head-on, neither can pass — pawns can't capture straight ahead.",
            board: "8/8/8/3pp3/4P3/8/8/8 w - - 0 1",
            spotlight: ["e4", "e5"],
          },
          {
            kind: "do",
            text: "Your e4 pawn is blocked by e5. But a neighbour waits on d5 — break the deadlock with a diagonal capture.",
            board: "8/8/8/3pp3/4P3/8/8/8 w - - 0 1",
            goal: { type: "move", uci: ["e4d5"] },
            spotlight: ["d5"],
            hint: "Capture diagonally: the e4 pawn takes on d5.",
          },
        ],
        tip: "A pawn blocked head-on can still strike sideways to break through.",
      },
      {
        id: "pawn-enpassant",
        title: "In Passing (En Passant)",
        blurb: "The en passant rule",
        icon: "✦",
        steps: [
          {
            kind: "say",
            text: "Now the trickiest rule in all of chess: en passant — French for 'in passing'.",
            board: "8/3p4/8/4P3/8/8/8/8 b - - 0 1",
            spotlight: ["e5"],
          },
          {
            kind: "say",
            text: "Your pawn waits on e5. Black's pawn sits on d7, about to dash two squares forward to d5 — trying to slip right past you.",
            board: "8/3p4/8/4P3/8/8/8/8 b - - 0 1",
            spotlight: ["d7", "e5"],
          },
          {
            kind: "do",
            text: "There it goes — rushing from d7 to d5, straight past your pawn. Now you may capture it in passing (en passant): land on the square it skipped, d6, and the runaway pawn is removed.",
            animateFrom: "8/3p4/8/4P3/8/8/8/8 b - - 0 1",
            board: "8/8/8/3pP3/8/8/8/8 w - d6 0 1",
            goal: { type: "move", uci: ["e5d6"] },
            spotlight: ["d6"],
            hint: "Move the e5 pawn diagonally to the empty d6 square. The black pawn on d5 vanishes — captured in passing (en passant).",
          },
          {
            kind: "say",
            text: "But you must do it at once. Wait even a single move and the chance to capture en passant is gone forever.",
          },
        ],
        tip: 'En passant ("in passing") captures a pawn that just dashed two squares past yours — landing on the square it skipped, and only immediately.',
      },
    ],
  },
  {
    id: "piece-plaza",
    name: "Piece Plaza",
    tagline: "Meet the whole army",
    icon: "♞",
    accent: "#567a9e",
    lessons: [
      {
        id: "knight-leap",
        title: "The Cavalry",
        blurb: "The knight's L-shaped leap",
        icon: "♞",
        steps: [
          {
            kind: "say",
            text: "The knight is the cavalry. It leaps in an L — two squares one way, then one across — and alone among the pieces, it jumps over anything in its path.",
            board: "8/8/8/8/4N3/8/8/8 w - - 0 1",
            spotlight: ["e4"],
          },
          {
            kind: "do",
            text: "Hop the knight to f6 — an L-shaped jump: two up, one across.",
            board: "8/8/8/8/4N3/8/8/8 w - - 0 1",
            goal: { type: "reach", square: "f6" },
            spotlight: ["f6"],
            hint: "From e4 the knight reaches f6: two squares up, one to the right.",
          },
        ],
        tip: "Knights move in an L and can jump over other pieces.",
      },
      {
        id: "bishop-diagonal",
        title: "The Glider",
        blurb: "Bishops rule the diagonals",
        icon: "♝",
        steps: [
          {
            kind: "say",
            text: "The bishop glides along diagonals as far as the road is clear. Each bishop keeps to one square colour for the entire game.",
            board: "8/8/8/8/4B3/8/8/8 w - - 0 1",
            spotlight: ["e4"],
          },
          {
            kind: "do",
            text: "Slide the bishop up its diagonal to h7.",
            board: "8/8/8/8/4B3/8/8/8 w - - 0 1",
            goal: { type: "reach", square: "h7" },
            spotlight: ["h7"],
            hint: "The light diagonal runs e4–f5–g6–h7.",
          },
        ],
        tip: "Bishops move diagonally and never change square colour.",
      },
      {
        id: "rook-lines",
        title: "The Battering Ram",
        blurb: "Rooks charge in straight lines",
        icon: "♜",
        steps: [
          {
            kind: "say",
            text: "The rook is a battering ram — it charges in straight lines, along ranks and files, as far as it likes.",
            board: "8/8/8/8/4R3/8/8/8 w - - 0 1",
            spotlight: ["e4"],
          },
          {
            kind: "do",
            text: "Send the rook straight up the e-file to e8.",
            board: "8/8/8/8/4R3/8/8/8 w - - 0 1",
            goal: { type: "reach", square: "e8" },
            spotlight: ["e8"],
            hint: "Rooks move in straight lines — e4 straight up to e8.",
          },
        ],
        tip: "Rooks move in straight lines along ranks and files.",
      },
      {
        id: "queen-power",
        title: "Her Majesty",
        blurb: "The most powerful piece",
        icon: "♛",
        steps: [
          {
            kind: "say",
            text: "The queen is rook and bishop combined — she sweeps any straight or diagonal line. Treat her with respect.",
            board: "8/1p6/8/8/4Q3/8/8/8 w - - 0 1",
            spotlight: ["e4", "b7"],
          },
          {
            kind: "do",
            text: "Use the queen's long reach to capture the pawn on b7.",
            board: "8/1p6/8/8/4Q3/8/8/8 w - - 0 1",
            goal: { type: "capture" },
            spotlight: ["b7"],
            hint: "The queen travels any straight or diagonal line — e4 to b7 is one diagonal: e4–d5–c6–b7.",
          },
        ],
        tip: "The queen combines rook and bishop — guard her, and use her reach.",
      },
      {
        id: "king-steps",
        title: "The Precious King",
        blurb: "Slow, but everything",
        icon: "♚",
        steps: [
          {
            kind: "say",
            text: "The king is precious but slow — he steps just one square in any direction. Lose him and the game is over, so keep him safe.",
            board: "8/8/8/8/4K3/8/8/8 w - - 0 1",
            spotlight: ["e4"],
          },
          {
            kind: "do",
            text: "Take one careful step — move the king up to e5.",
            board: "8/8/8/8/4K3/8/8/8 w - - 0 1",
            goal: { type: "reach", square: "e5" },
            spotlight: ["e5"],
            hint: "The king moves one square in any direction: e4 to e5.",
          },
        ],
        tip: "The king moves one square at a time — protect him above all else.",
      },
    ],
  },
  {
    id: "coordinate-heights",
    name: "Coordinate Heights",
    tagline: "Read the board",
    icon: "▦",
    accent: "#8b5cf6",
    lessons: [
      {
        id: "board-files-ranks",
        title: "Every Square Has a Name",
        blurb: "Files, ranks & addresses",
        icon: "▦",
        steps: [
          {
            kind: "say",
            text: "Every square has an address. Columns are files, labelled a to h. Rows are ranks, numbered 1 to 8.",
            board: "8/8/8/8/8/8/8/N7 w - - 0 1",
            spotlight: ["a1"],
          },
          {
            kind: "do",
            text: "A square's name is its file letter then its rank number. Move the knight to c2.",
            board: "8/8/8/8/8/8/8/N7 w - - 0 1",
            goal: { type: "reach", square: "c2" },
            spotlight: ["c2"],
            hint: "Files run left to right a–h; ranks run bottom to top 1–8. c2 is the third file, second rank.",
          },
        ],
        tip: "A square's name is its file letter then its rank number, like e4.",
      },
      {
        id: "board-diagonals",
        title: "The Long Roads",
        blurb: "Diagonals corner to corner",
        icon: "⟋",
        steps: [
          {
            kind: "say",
            text: "Diagonals are the slanting roads bishops and queens love. The longest stretch from corner to corner.",
            board: "8/8/8/8/8/8/8/B7 w - - 0 1",
            spotlight: ["a1"],
          },
          {
            kind: "do",
            text: "Travel the long diagonal from a1 all the way to h8.",
            board: "8/8/8/8/8/8/8/B7 w - - 0 1",
            goal: { type: "reach", square: "h8" },
            spotlight: ["h8"],
            hint: "a1–b2–c3–d4–e5–f6–g7–h8 is the longest diagonal on the board.",
          },
        ],
        tip: "Diagonals run corner-ward; a1–h8 and a8–h1 are the longest.",
      },
    ],
  },
  {
    id: "teamwork-glade",
    name: "Teamwork Glade",
    tagline: "Pieces working together",
    icon: "✦",
    accent: "#C5A059",
    lessons: [
      {
        id: "combine-hanging",
        title: "Don't Hang a Piece",
        blurb: "Spot squares under fire",
        icon: "⚠",
        steps: [
          {
            kind: "say",
            text: "A piece sitting where the enemy can take it for nothing is 'hanging' — a gift you never meant to give.",
            board: "3r4/8/8/8/8/4N3/8/8 w - - 0 1",
            spotlight: ["d8"],
          },
          {
            kind: "say",
            text: "This rook on d8 guards the entire d-file. Any piece you place on that file is in danger.",
            board: "3r4/8/8/8/8/4N3/8/8 w - - 0 1",
            spotlight: ["d8", "d5", "d4", "d3", "d2", "d1"],
          },
          {
            kind: "do",
            text: "Develop your knight actively — but stay out of the rook's reach. Leap to f5.",
            board: "3r4/8/8/8/8/4N3/8/8 w - - 0 1",
            goal: { type: "move", uci: ["e3f5"] },
            spotlight: ["f5"],
            hangingHints: true,
            hint: "Choose f5 — active and safe. Avoid d-file squares like d5; the rook would snap your knight up.",
          },
        ],
        tip: "Before every move, ask: can the enemy take this piece for free? Don't leave pieces hanging.",
      },
    ],
  },
  {
    id: "castle-keep",
    name: "Castle Keep",
    tagline: "Tuck your king away",
    icon: "♖",
    accent: "#9c6f4a",
    lessons: [
      {
        id: "castle-kingside",
        title: "Castling",
        blurb: "The king's special move",
        icon: "♖",
        steps: [
          {
            kind: "say",
            text: "Castling is a special move that does two good things at once: it hides your king in the corner and brings a sleepy rook into the game.",
            board: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1",
            spotlight: ["e1", "h1"],
          },
          {
            kind: "do",
            text: "To castle kingside, move your KING two squares toward the near rook — to g1. The rook jumps over to f1 by itself.",
            board: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1",
            goal: { type: "move", uci: ["e1g1"] },
            spotlight: ["g1"],
            hint: "Move the king from e1 to g1 (two squares). The rook hops to f1 automatically.",
          },
          {
            kind: "do",
            text: "You can also castle the other way. Move your king two squares toward the far rook — to c1 — and that rook leaps to d1.",
            board: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1",
            goal: { type: "move", uci: ["e1c1"] },
            spotlight: ["c1"],
            hint: "Move the king from e1 to c1. The a1 rook jumps to d1.",
          },
          {
            kind: "say",
            text: "Castle early to keep your king safe! But you can't castle while in check, through a square the enemy attacks, or after your king or that rook has already moved.",
          },
        ],
        tip: "Castling moves your king to safety and activates a rook — usually do it in the first few moves.",
      },
    ],
  },
  {
    id: "first-moves",
    name: "First Moves",
    tagline: "Start a game well",
    icon: "⚑",
    accent: "#5b8c5a",
    lessons: [
      {
        id: "game-center",
        title: "Your First Game",
        blurb: "A guided opening",
        icon: "⚑",
        steps: [
          {
            kind: "say",
            text: "Let's play the start of a real game together. I'll guide each move and tell you why it's good.",
            board: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w - - 0 1",
          },
          {
            kind: "do",
            text: "Push your king's pawn two squares to e4. It grabs the center and frees both your bishop and your queen.",
            board: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w - - 0 1",
            goal: { type: "move", uci: ["e2e4"] },
            spotlight: ["e4"],
            hint: "Move the e2 pawn forward two squares to e4.",
          },
          {
            kind: "do",
            text: "Black mirrors you with ...e5. Now develop a knight to f3 — it jumps out and attacks Black's e5 pawn.",
            animateFrom: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
            board: "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
            goal: { type: "move", uci: ["g1f3"] },
            spotlight: ["f3"],
            hint: "Move the knight from g1 to f3.",
          },
          {
            kind: "do",
            text: "Black defends with ...Nc6. Bring your bishop to c4, aiming straight at f7 — the weakest square near Black's king.",
            animateFrom: "rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2",
            board: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3",
            goal: { type: "move", uci: ["f1c4"] },
            spotlight: ["c4"],
            hint: "Move the bishop from f1 to c4.",
          },
          {
            kind: "do",
            text: "Black develops a knight to f6. Your pieces are out — now get safe. Castle kingside: move your king to g1.",
            animateFrom: "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3",
            board: "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
            goal: { type: "move", uci: ["e1g1"] },
            spotlight: ["g1"],
            hint: "Castle: move the king from e1 to g1.",
          },
          {
            kind: "do",
            text: "Black plays ...Bc5. Finish your setup with d3 — it props up your e4 pawn and opens a path for your last bishop.",
            animateFrom: "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4",
            board: "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 6 5",
            goal: { type: "move", uci: ["d2d3"] },
            spotlight: ["d3"],
            hint: "Move the d2 pawn one square to d3.",
          },
          {
            kind: "say",
            text: "Beautiful! You took the center, developed your knights and bishop, and castled your king to safety. That's a perfect opening.",
          },
        ],
        tip: "In the opening: grab the center, develop your knights and bishops, then castle your king to safety.",
      },
      {
        id: "game-queenpawn",
        title: "A Different Start",
        blurb: "Another guided opening",
        icon: "⚑",
        steps: [
          {
            kind: "say",
            text: "Not every game starts with the king's pawn. Let's try a calm, solid setup with the queen's pawn instead.",
            board: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w - - 0 1",
          },
          {
            kind: "do",
            text: "Open with d4 — the queen's pawn. It claims the center, just like e4 does.",
            board: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w - - 0 1",
            goal: { type: "move", uci: ["d2d4"] },
            spotlight: ["d4"],
            hint: "Move the d2 pawn two squares to d4.",
          },
          {
            kind: "do",
            text: "Black answers ...d5. Develop your knight to f3 — knights love to come out early.",
            animateFrom: "rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1",
            board: "rnbqkbnr/ppp1pppp/8/3p4/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 2",
            goal: { type: "move", uci: ["g1f3"] },
            spotlight: ["f3"],
            hint: "Move the knight from g1 to f3.",
          },
          {
            kind: "do",
            text: "Black develops ...Nf6. Now bring your bishop OUT to f4, before you block it in with pawns.",
            animateFrom: "rnbqkbnr/ppp1pppp/8/3p4/3P4/5N2/PPP1PPPP/RNBQKB1R b KQkq - 1 2",
            board: "rnbqkb1r/ppp1pppp/5n2/3p4/3P4/5N2/PPP1PPPP/RNBQKB1R w KQkq - 2 3",
            goal: { type: "move", uci: ["c1f4"] },
            spotlight: ["f4"],
            hint: "Move the c1 bishop out to f4.",
          },
          {
            kind: "do",
            text: "Black plays ...e6. Play e3 — a small step that opens a path for your other bishop.",
            animateFrom: "rnbqkb1r/ppp1pppp/5n2/3p4/3P1B2/5N2/PPP1PPPP/RN1QKB1R b KQkq - 3 3",
            board: "rnbqkb1r/ppp2ppp/4pn2/3p4/3P1B2/5N2/PPP1PPPP/RN1QKB1R w KQkq - 0 4",
            goal: { type: "move", uci: ["e2e3"] },
            spotlight: ["e3"],
            hint: "Move the e2 pawn one square to e3.",
          },
          {
            kind: "do",
            text: "Black develops ...Be7. Develop your bishop to d3, pointing at Black's kingside. Next you'd castle.",
            animateFrom: "rnbqkb1r/ppp2ppp/4pn2/3p4/3P1B2/4PN2/PPP2PPP/RN1QKB1R b KQkq - 0 4",
            board: "rnbqk2r/ppp1bppp/4pn2/3p4/3P1B2/4PN2/PPP2PPP/RN1QKB1R w KQkq - 1 5",
            goal: { type: "move", uci: ["f1d3"] },
            spotlight: ["d3"],
            hint: "Move the f1 bishop to d3.",
          },
          {
            kind: "say",
            text: "Same ideas, different pawns: center, knights, bishops, and a safe king coming up. Good openings all rhyme.",
          },
        ],
        tip: "The opening plan is always the same — center, develop, castle — no matter which pawn you start with.",
      },
    ],
  },
  {
    id: "watchful-eyes",
    name: "Watchful Eyes",
    tagline: "Who's protecting who",
    icon: "🛡",
    accent: "#c77d4a",
    lessons: [
      {
        id: "coord-safe-take",
        title: "Safe to Take?",
        blurb: "Take what's free",
        icon: "🛡",
        steps: [
          {
            kind: "say",
            text: "Before you capture, check: is the piece guarded? Take what's free; leave what would cost you.",
            board: "4k3/7p/2p3p1/4N3/8/8/8/4K3 w - - 0 1",
            spotlight: ["c6", "g6"],
          },
          {
            kind: "do",
            text: "Your knight can grab either black pawn. But the g6 pawn is guarded by the h7 pawn — take it and you lose your knight! Capture the free one on c6 instead.",
            board: "4k3/7p/2p3p1/4N3/8/8/8/4K3 w - - 0 1",
            goal: { type: "move", uci: ["e5c6"] },
            spotlight: ["c6"],
            hangingHints: true,
            hint: "Capture on c6 — nothing guards it. Avoid g6: the h7 pawn would take your knight back.",
          },
          {
            kind: "say",
            text: "Nicely judged. A capture is only good when the enemy can't take back for free — always look for the defender first.",
          },
        ],
        tip: "Before capturing, check who's guarding it. Take undefended pieces; avoid guarded ones unless you come out ahead.",
      },
      {
        id: "coord-guard",
        title: "Guard Your Pieces",
        blurb: "Add a defender",
        icon: "🛡",
        steps: [
          {
            kind: "say",
            text: "When one of your pieces is attacked, you don't always have to run. Sometimes you can simply guard it.",
            board: "4k3/8/3p4/4N3/8/8/3P1P2/4K3 w - - 0 1",
            spotlight: ["e5", "d6"],
          },
          {
            kind: "do",
            text: "Black's d6 pawn attacks your knight on e5, and nothing defends it. Push a pawn to f4 so it guards the knight — now if Black takes, you take right back.",
            board: "4k3/8/3p4/4N3/8/8/3P1P2/4K3 w - - 0 1",
            goal: { type: "move", uci: ["f2f4", "d2d4"] },
            spotlight: ["f4", "d4"],
            hint: "Move a pawn to f4 (or d4) — it will defend the knight on e5.",
          },
          {
            kind: "say",
            text: "Now your pieces protect each other. A defended piece is a safe piece — make your army work as a team.",
          },
        ],
        tip: "If a piece is attacked, you can guard it with another piece instead of moving it away.",
      },
    ],
  },
  {
    id: "checkmate-manor",
    name: "Checkmate Manor",
    tagline: "How to win the game",
    icon: "♚",
    accent: "#b5485e",
    lessons: [
      {
        id: "mate-what-is",
        title: "What Is Checkmate?",
        blurb: "Ending the game",
        icon: "♚",
        steps: [
          {
            kind: "say",
            text: "You win chess by checkmate. Checkmate means the enemy king is under attack and has no way out — it can't move to safety, block the attack, or capture the attacker.",
            board: "4k3/8/3K4/8/8/8/4Q3/8 w - - 0 1",
            spotlight: ["e8", "e2"],
          },
          {
            kind: "do",
            text: "Bring your queen to e7, right in front of the black king. Your own king on d6 guards her, so the king can't capture her — and every escape square is covered. That's checkmate!",
            board: "4k3/8/3K4/8/8/8/4Q3/8 w - - 0 1",
            goal: { type: "move", uci: ["e2e7"] },
            spotlight: ["e7"],
            hint: "Move the queen from e2 up to e7. The king on d6 protects her.",
          },
          {
            kind: "say",
            text: "Game over — that's a win! The king is attacked and has nowhere to run, nothing to block with, and can't take the queen. Checkmate.",
          },
        ],
        tip: "Checkmate = the king is attacked and cannot escape, block, or capture. That wins the game.",
      },
      {
        id: "mate-back-rank",
        title: "Back-Rank Mate",
        blurb: "Trapped by its own pawns",
        icon: "♜",
        steps: [
          {
            kind: "say",
            text: "A king castled behind its own pawns can get trapped on the back row. A rook or queen sliding to that row can deliver mate.",
            board: "6k1/5ppp/8/8/8/8/8/4R1K1 w - - 0 1",
            spotlight: ["g8", "f7", "g7", "h7"],
          },
          {
            kind: "do",
            text: "The black king is boxed in by its own f7, g7 and h7 pawns — it can't step up. Send your rook to e8 to deliver mate along the back rank.",
            board: "6k1/5ppp/8/8/8/8/8/4R1K1 w - - 0 1",
            goal: { type: "move", uci: ["e1e8"] },
            spotlight: ["e8"],
            hint: "Move the rook from e1 all the way to e8.",
          },
          {
            kind: "say",
            text: "Checkmate! The rook attacks the king along the back rank, and the king's own pawns block every escape. This is the famous back-rank mate.",
          },
        ],
        tip: "Watch for back-rank mates — a king walled in by its own pawns can be mated by a rook or queen on that row.",
      },
      {
        id: "mate-two-rooks",
        title: "The Rook Ladder",
        blurb: "Two rooks mate alone",
        icon: "♖",
        steps: [
          {
            kind: "say",
            text: "Two rooks can checkmate a lone king all by themselves, like climbing a ladder — one rook fences the king in, the other delivers mate.",
            board: "k7/6R1/8/8/8/8/8/4K2R w - - 0 1",
            spotlight: ["a8", "g7"],
          },
          {
            kind: "do",
            text: "Your rook on g7 already traps the black king on the edge — it can't step down to the 7th row. Bring your other rook to h8 to finish: checkmate!",
            board: "k7/6R1/8/8/8/8/8/4K2R w - - 0 1",
            goal: { type: "move", uci: ["h1h8"] },
            spotlight: ["h8"],
            hint: "Move the h1 rook up to h8.",
          },
          {
            kind: "say",
            text: "Checkmate! One rook seals the row in front of the king, the other attacks along its row. Two rooks are a deadly team.",
          },
        ],
        tip: "Two rooks mate a lone king with a ladder: one cuts off a row, the other checks on the next.",
      },
    ],
  },
];
